# Start with an OpenJDK base image with JDK 17
FROM openjdk:17-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the jar file to the working directory
COPY target/jwt-auth-server-0.1.0-SNAPSHOT.jar /app/app.jar

# Copy the application.yml and keycloak-server.json to the appropriate directory
COPY src/main/resources/application.uat-yml /app/application.yml
COPY src/main/resources/sao-tsea-realm.json /app/sao-tsea-realm.json
COPY src/main/resources/META-INF/keycloak-server.json /app/META-INF/keycloak-server.json
COPY src/main/resources/mytest.jks /app/mytest.jks

# The port your application runs on
EXPOSE 8083

ENV JAVA_OPTS="-Dserver.forward-headers-strategy=native"

# Set the entrypoint to run your jar file with JAVA_OPTS
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]
